<?php
  define('PLURK_LANG_ENGLISH', 'en');			// English
  define('PLURK_LANG_PORTUGUESE', 'pt_BR');		// Português
  define('PLURK_LANG_CHINESE_SIMPLIFIED', 'cn');	// 簡體中文
  define('PLURK_LANG_CHINESE_TRADITIONAL', 'tr_ch');	// 正體中文
  define('PLURK_LANG_CATALAN', 'ca');			// Català
  define('PLURK_LANG_JAPANESE', 'ja');			// 日本語
  define('PLURK_LANG_GREEK', 'el');			// Ελληνικά
  define('PLURK_LANG_DANISH', 'dk');			// Dansk
  define('PLURK_LANG_DEUSTSCH', 'de');			// Deutsch
  define('PLURK_LANG_SPANISH', 'es');			// Español
  define('PLURK_LANG_SWEDISH', 'sv');			// Svenska
  define('PLURK_LANG_NORWEGIAN', 'nb');			// Norsk bokmål
/*
'hi': 'Hindi'
'ro': 'Română'
'hr': 'Hrvatski'
'fr': 'Français'
'ru': 'Pусский'
'it': 'Italiano '
'he': 'עברית'
'hu': 'Magyar'
'ne': 'Nederlands'
'th': 'ไทย'
'ta_fp': 'Filipino'
'in': 'Bahasa Indonesia'
'pl': 'Polski'
'ar': 'العربية'
'fi': 'Finnish'
'tr': 'Türkçe'
'ga': 'Gaeilge'
'sk': 'Slovenský'
'uk': 'українська'
*/

?>