<?php
/*
 *  ybot.php - a plurk bot use php-plurk-api
 *
 *  Copyright (C) 2012 Wei-Chen Lai <abev66@gmail.com>
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/

  define('PLURK_LANG_ENGLISH', 'en');			// English
  define('PLURK_LANG_PORTUGUESE', 'pt_BR');		// Português
  define('PLURK_LANG_CHINESE_SIMPLIFIED', 'cn');	// 簡體中文
  define('PLURK_LANG_CHINESE_TRADITIONAL', 'tr_ch');	// 正體中文
  define('PLURK_LANG_CATALAN', 'ca');			// Català
  define('PLURK_LANG_JAPANESE', 'ja');			// 日本語
  define('PLURK_LANG_GREEK', 'el');			// Ελληνικά
  define('PLURK_LANG_DANISH', 'dk');			// Dansk
  define('PLURK_LANG_DEUSTSCH', 'de');			// Deutsch
  define('PLURK_LANG_SPANISH', 'es');			// Español
  define('PLURK_LANG_SWEDISH', 'sv');			// Svenska
  define('PLURK_LANG_NORWEGIAN', 'nb');			// Norsk bokmål
/*
'hi': 'Hindi'
'ro': 'Română'
'hr': 'Hrvatski'
'fr': 'Français'
'ru': 'Pусский'
'it': 'Italiano '
'he': 'עברית'
'hu': 'Magyar'
'ne': 'Nederlands'
'th': 'ไทย'
'ta_fp': 'Filipino'
'in': 'Bahasa Indonesia'
'pl': 'Polski'
'ar': 'العربية'
'fi': 'Finnish'
'tr': 'Türkçe'
'ga': 'Gaeilge'
'sk': 'Slovenský'
'uk': 'українська'
*/

?>